---
- name: file module demo
  hosts: First
  vars:
    myfile: "/etc"
  become: false
  tasks:
    - name: check permission
      ansible.builtin.file:
        path: "/etc"
        owner: "root"
        group: "root"
        mode: '755'
